version: '3.9'

services:
  business-communication:
    build: .
    container_name: business-communication
    ports:
      - "${PORT}:8080"
    volumes:
      - ./BusinessCommunication/prompt.txt:/app/prompt.txt:ro
    environment:
      - Settings__BusinessCommunication__ApplicationName=${Settings__BusinessCommunication__ApplicationName}
      - Settings__HttpSettings__ApiMetaUrl=${Settings__HttpSettings__ApiMetaUrl}
      - Settings__HttpSettings__BusinessManagerPersistanceUrl=${Settings__HttpSettings__BusinessManagerPersistanceUrl}
      - Settings__HttpSettings__ApiModelUrl=${Settings__HttpSettings__ApiModelUrl}
      - Settings__HttpSettings__MetaAccessKey=${Settings__HttpSettings__MetaAccessKey}
      - Settings__HttpSettings__MetaKeyId=${Settings__HttpSettings__MetaKeyId}
      - Settings__HttpSettings__GoogleApiKey=${Settings__HttpSettings__GoogleApiKey}
      - Settings__CommunicationSettings__MessageProduct=${Settings__CommunicationSettings__MessageProduct}
      - Settings__CommunicationSettings__RecipientType=${Settings__CommunicationSettings__RecipientType}
      - Settings__CommunicationSettings__MessageType=${Settings__CommunicationSettings__MessageType}
      - Settings__CommunicationSettings__GoogleSheetsSettings__ServiceAccountJson=${Settings__CommunicationSettings__GoogleSheetsSettings__ServiceAccountJson}
    restart: always
